require("dotenv").config();
const mongoose = require("mongoose");
const Plant = require("./models/Plant");

const newPlants = [
  { name: "Marigold",           category: "Flower Plants",  type: "Outdoor Plant",      emotion: "Festive",    occasion: ["Festival","Decoration"], availability: "All season", pricePerStem: 49,  price: 49,  original: 89,  discount: 45, priceRange: { min: 30,  max: 80  }, color: "Orange", image: "", img: "🌼", city: "Bhubaneswar", nursery: "Kolkata Phool Bazar",           inStock: true },
  { name: "African Daisy",      category: "Flower Plants",  type: "Outdoor Plant",      emotion: "Cheerful",   occasion: ["Garden"],                availability: "Seasonal",   pricePerStem: 129, price: 129, original: 199, discount: 35, priceRange: { min: 80,  max: 200 }, color: "Orange", image: "", img: "🌸", city: "Bhubaneswar", nursery: "Green Valley Nursery, Pune",    inStock: true },
  { name: "Rose (Pink)",        category: "Flower Plants",  type: "Garden Plant",       emotion: "Love",       occasion: ["Gift"],                  availability: "All season", pricePerStem: 149, price: 149, original: 249, discount: 40, priceRange: { min: 100, max: 250 }, color: "Pink",   image: "", img: "🌹", city: "Bhubaneswar", nursery: "Roots & Leaves, Bangalore",     inStock: true },
  { name: "Rose (Red Cluster)", category: "Flower Plants",  type: "Garden Plant",       emotion: "Passion",    occasion: ["Valentine"],             availability: "All season", pricePerStem: 159, price: 159, original: 249, discount: 36, priceRange: { min: 100, max: 250 }, color: "Red",    image: "", img: "🌹", city: "Bhubaneswar", nursery: "Kolkata Phool Bazar",           inStock: true },
  { name: "Hibiscus",           category: "Flower Plants",  type: "Outdoor Plant",      emotion: "Beauty",     occasion: ["Garden"],                availability: "All season", pricePerStem: 150, price: 150, original: 249, discount: 40, priceRange: { min: 100, max: 300 }, color: "Red",    image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774897500/pexels-kolkatarchobiwala-30897108_rgfkmk.jpg", img: "🌺", city: "Bhubaneswar", nursery: "City Greens Wholesale, Mumbai", inStock: true },
  { name: "Sunflower",          category: "Flower Plants",  type: "Outdoor Plant",      emotion: "Happiness",  occasion: ["Garden"],                availability: "Seasonal",   pricePerStem: 100, price: 100, original: 159, discount: 37, priceRange: { min: 60,  max: 150 }, color: "Yellow", image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774897504/pexels-rahul-handa-31612239-36632680_xleunk.jpg", img: "🌻", city: "Bhubaneswar", nursery: "Roots & Leaves, Bangalore",     inStock: true },
  { name: "Dahlia",             category: "Flower Plants",  type: "Outdoor Plant",      emotion: "Elegance",   occasion: ["Garden"],                availability: "Seasonal",   pricePerStem: 120, price: 120, original: 199, discount: 40, priceRange: { min: 80,  max: 200 }, color: "Pink",   image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774897503/pexels-selin-sevinc-1827151337-35273594_nv6gou.jpg", img: "🌺", city: "Bhubaneswar", nursery: "Green Valley Nursery, Pune",    inStock: true },
  { name: "Coconut Tree",       category: "Outdoor Plants", type: "Fruit Tree",         emotion: "Tropical",   occasion: ["Gardening"],             availability: "All season", pricePerStem: 500, price: 500, original: 799, discount: 37, priceRange: { min: 300, max: 1000}, color: "Green",  image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774900043/pexels-jess-vide-4609254_ws6gkl.jpg", img: "🌴", city: "Bhubaneswar", nursery: "Delhi Plant Bazaar",            inStock: true },
  { name: "Mango Tree",         category: "Outdoor Plants", type: "Fruit Tree",         emotion: "Happiness",  occasion: ["Farming"],               availability: "Seasonal",   pricePerStem: 400, price: 400, original: 649, discount: 38, priceRange: { min: 250, max: 800 }, color: "Green",  image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774900048/pexels-neydi-gastelo-781266070-19087708_mc9i1d.jpg", img: "🌳", city: "Bhubaneswar", nursery: "Delhi Plant Bazaar",            inStock: true },
  { name: "Guava Plant",        category: "Outdoor Plants", type: "Fruit Plant",        emotion: "Freshness",  occasion: ["Home Garden"],           availability: "All season", pricePerStem: 180, price: 180, original: 299, discount: 40, priceRange: { min: 120, max: 350 }, color: "Green",  image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774900044/pexels-zaryabhaider-36706060_apbltf.jpg", img: "🍃", city: "Bhubaneswar", nursery: "Green Earth Nursery",           inStock: true },
  { name: "Lemon Plant",        category: "Outdoor Plants", type: "Fruit Plant",        emotion: "Freshness",  occasion: ["Home Garden"],           availability: "All season", pricePerStem: 150, price: 150, original: 249, discount: 40, priceRange: { min: 100, max: 300 }, color: "Yellow", image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774900044/pexels-vera-rishkevich-1586519505-36371415_jtsrnu.jpg", img: "🍋", city: "Bhubaneswar", nursery: "Green Earth Nursery",           inStock: true },
  { name: "Snake Plant",        category: "Air Purifying",  type: "Air Purifying Plant",emotion: "Protection", occasion: ["Office"],                availability: "All season", pricePerStem: 180, price: 180, original: 299, discount: 40, priceRange: { min: 120, max: 350 }, color: "Green",  image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774900057/pexels-msaimakin-29218657_aajsqx.jpg", img: "🌱", city: "Bhubaneswar", nursery: "Regional Plant Resource Center", inStock: true },
  { name: "Lucky Bamboo",       category: "Indoor Plants",  type: "Decor Plant",        emotion: "Good Luck",  occasion: ["Gift"],                  availability: "All season", pricePerStem: 100, price: 100, original: 179, discount: 44, priceRange: { min: 80,  max: 300 }, color: "Green",  image: "https://res.cloudinary.com/deixioyzo/image/upload/v1774900051/pexels-soc-nang-d-ng-2150345854-32627780_rzvsi6.jpg", img: "🎋", city: "Bhubaneswar", nursery: "Garden City Nursery",           inStock: true },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("Connected to MongoDB");
  await Plant.deleteMany({});
  console.log("Cleared old plants");
  await Plant.insertMany(newPlants);
  console.log(`✅ Inserted ${newPlants.length} new plants successfully!`);
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
